
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: testejera_development

test:
  <<: *default
  database: testejera_test

production:
  <<: *default
  database: testejera_production
  username: testejera
  password: <%= ENV["TESTEJERA_DATABASE_PASSWORD"] %>
